spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mmcosm_dev
    username: maze
    password: maze
    driver-class-name: com.mysql.jdbc.Driver
security:
  basic:
    enabled: true
  user:
    name: user
    password: 60361173a
mybatis:
  type-aliases-package: cn.mazekkkk.cloud.product.dao.mapper
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
tm:
  manager:
    url: http://localhost:8899/tx/manager/
