spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/cloud_order
    username: root
    password: liugeyi
    driver-class-name: com.mysql.jdbc.Driver
security:
  basic:
    enabled: true
  user:
    name: user
    password: 60361173a
mybatis:
  type-aliases-package: cn.mazekkkk.cloud.order.dao.mapper
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
tm:
  manager:
    url: http://192.168.99.100:8899/tx/manager/
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@192.168.99.100:8761/eureka/,http://user:password123@192.168.99.100:8762/eureka/
  instance:
    prefer-ip-address: true
logging:
  level: com.codingapi=debug
